import {useTranslation} from 'react-i18next';
import LegalContent from '@/components/landing/legal/LegalContent';
import React from 'react';

export default function Privacy() {
	const {t} = useTranslation();
	return (
		<LegalContent>
			<h1 className="font-sans text-3xl font-medium tracking-tight">
				{t('legal.privacyPolicy')}
			</h1>
			<p>{t('legal.privacy.block001')}</p>
			<p>{t('legal.privacy.block002')}</p>
			<p>{t('legal.privacy.block003')}</p>
			<h2>{t('legal.privacy.block004')}</h2>
			<h3>{t('legal.privacy.block005')}</h3>
			<p>{t('legal.privacy.block006')}</p>
			<h3>{t('legal.privacy.block007')}</h3>
			<p>{t('legal.privacy.block008')}</p>
			<ul>
				<li>
					<p>
						<strong>{t('navigation.account')}</strong> {t('legal.privacy.block009')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block010')}</strong>
						{t('legal.privacy.block011')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block012')}</strong> {t('legal.privacy.block013')}
					</p>
					<p>{t('legal.privacy.block014')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block015')}</strong>
						{t('legal.privacy.block016')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block017')}</strong> {t('legal.privacy.block018')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block019')}</strong> {t('legal.privacy.block020')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block021')}</strong>
						{t('legal.privacy.block022')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block023')}</strong> {t('legal.privacy.block024')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block025')}</strong> {t('legal.privacy.block026')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block027')}</strong> {t('legal.privacy.block028')}
					</p>
					<p>{t('legal.privacy.block029')}</p>
					<p>{t('legal.privacy.block030')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block031')}</strong>
						{t('legal.privacy.block032')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block033')}</strong> {t('legal.privacy.block034')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block035')}</strong> {t('legal.privacy.block036')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block037')}</strong> {t('legal.privacy.block038')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block039')}</strong> {t('legal.privacy.block040')}{' '}
						<a href="/" rel="external nofollow noopener" target="_blank">
							{t('legal.privacy.block041')}
						</a>
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block042')}</strong> {t('legal.privacy.block043')}
					</p>
					<p>{t('legal.privacy.block044')}</p>
				</li>
			</ul>
			<h2>{t('legal.privacy.block045')}</h2>
			<h3>{t('legal.privacy.block046')}</h3>
			<h4>{t('legal.privacy.block047')}</h4>
			<p>{t('legal.privacy.block048')}</p>
			<ul>
				<li>
					<p>{t('legal.privacy.block049')}</p>
				</li>
				<li>
					<p>{t('auth.username')}</p>
				</li>
				<li>
					<p>{t('legal.privacy.block050')}</p>
				</li>
			</ul>
			<h4>{t('legal.privacy.block051')}</h4>
			<p>{t('legal.privacy.block052')}</p>
			<p>{t('legal.privacy.block053')}</p>
			<p>{t('legal.privacy.block054')}</p>
			<p>{t('legal.privacy.block055')}</p>
			<h4>{t('legal.privacy.block056')}</h4>
			<p>{t('legal.privacy.block057')}</p>
			<ul>
				<li>
					<strong>{t('legal.privacy.block058')}</strong> {t('legal.privacy.block059')}
				</li>
				<li>
					<strong>{t('legal.privacy.block060')}</strong> {t('legal.privacy.block061')}{' '}
					<a
						href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_"
						rel="external nofollow noopener"
						target="_blank"
					>
						{t('legal.privacy.block062')}
					</a>
				</li>
				<li>
					<strong>{t('legal.privacy.block063')}</strong> {t('legal.privacy.block064')}
				</li>
			</ul>
			<p>
				{t('legal.privacy.block065')}{' '}
				<a href="https://www.termsfeed.com/blog/cookies/" target="_blank">
					{t('legal.privacy.block066')}
				</a>
				{t('legal.privacy.block067')}
			</p>
			<p>{t('legal.privacy.block068')}</p>
			<ul>
				<li>
					<p>
						<strong>{t('legal.privacy.block069')}</strong>
					</p>
					<p>{t('legal.privacy.block070')}</p>
					<p>{t('legal.privacy.block071')}</p>
					<p>{t('legal.privacy.block072')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block073')}</strong>
					</p>
					<p>{t('legal.privacy.block074')}</p>
					<p>{t('legal.privacy.block075')}</p>
					<p>{t('legal.privacy.block076')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block077')}</strong>
					</p>
					<p>{t('legal.privacy.block078')}</p>
					<p>{t('legal.privacy.block079')}</p>
					<p>{t('legal.privacy.block080')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block081')}</strong>
					</p>
					<p>{t('legal.privacy.block082')}</p>
					<p>{t('legal.privacy.block083')}</p>
					<p>{t('legal.privacy.block084')}</p>
				</li>
			</ul>
			<p>{t('legal.privacy.block085')}</p>
			<h3>{t('legal.privacy.block086')}</h3>
			<p>{t('legal.privacy.block087')}</p>
			<ul>
				<li>
					<p>
						<strong>{t('legal.privacy.block088')}</strong>
						{t('legal.privacy.block089')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block090')}</strong> {t('legal.privacy.block091')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block092')}</strong> {t('legal.privacy.block093')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block094')}</strong> {t('legal.privacy.block095')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block096')}</strong> {t('legal.privacy.block097')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block098')}</strong> {t('legal.privacy.block099')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block100')}</strong> {t('legal.privacy.block101')}
					</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block102')}</strong>
						{t('legal.privacy.block103')}
					</p>
				</li>
			</ul>
			<p>{t('legal.privacy.block104')}</p>
			<ul>
				<li>
					<strong>{t('legal.privacy.block105')}</strong> {t('legal.privacy.block106')}
				</li>
				<li>
					<strong>{t('legal.privacy.block107')}</strong> {t('legal.privacy.block108')}
				</li>
				<li>
					<strong>{t('legal.privacy.block109')}</strong> {t('legal.privacy.block110')}
				</li>
				<li>
					<strong>{t('legal.privacy.block111')}</strong> {t('legal.privacy.block112')}
				</li>
				<li>
					<strong>{t('legal.privacy.block113')}</strong> {t('legal.privacy.block114')}
				</li>
				<li>
					<strong>{t('legal.privacy.block115')}</strong>
					{t('legal.privacy.block116')}
				</li>
			</ul>
			<h3>{t('legal.privacy.block117')}</h3>
			<p>{t('legal.privacy.block118')}</p>
			<p>{t('legal.privacy.block119')}</p>
			<h3>{t('legal.privacy.block120')}</h3>
			<p>{t('legal.privacy.block121')}</p>
			<p>{t('legal.privacy.block122')}</p>
			<p>{t('legal.privacy.block123')}</p>
			<h3>{t('legal.privacy.block124')}</h3>
			<h4>{t('legal.privacy.block125')}</h4>
			<p>{t('legal.privacy.block126')}</p>
			<h4>{t('legal.privacy.block127')}</h4>
			<p>{t('legal.privacy.block128')}</p>
			<h4>{t('legal.privacy.block129')}</h4>
			<p>{t('legal.privacy.block130')}</p>
			<ul>
				<li>{t('legal.privacy.block131')}</li>
				<li>{t('legal.privacy.block132')}</li>
				<li>{t('legal.privacy.block133')}</li>
				<li>{t('legal.privacy.block134')}</li>
				<li>{t('legal.privacy.block135')}</li>
			</ul>
			<h3>{t('legal.privacy.block136')}</h3>
			<p>{t('legal.privacy.block137')}</p>
			<h2>{t('legal.privacy.block138')}</h2>
			<p>{t('legal.privacy.block139')}</p>
			<h3>{t('legal.privacy.block140')}</h3>
			<p>{t('legal.privacy.block141')}</p>
			<ul>
				<li>
					<p>
						<strong>{t('legal.privacy.block142')}</strong>
					</p>
					<p>{t('legal.privacy.block143')}</p>
					<p>{t('legal.privacy.block144')}</p>
					<p>
						{t('legal.privacy.block145')}{' '}
						<a
							href="https://policies.google.com/privacy"
							rel="external nofollow noopener"
							target="_blank"
						>
							{t('legal.privacy.block146')}
						</a>
					</p>
				</li>
			</ul>
			<h3>{t('legal.privacy.block147')}</h3>
			<p>{t('legal.privacy.block148')}</p>
			<p>{t('legal.privacy.block149')}</p>
			<ul>
				<li>
					<p>
						<strong>{t('legal.privacy.block150')}</strong>
					</p>
					<p>
						{t('legal.privacy.block151')}{' '}
						<a
							href="https://aws.amazon.com/privacy/"
							rel="external nofollow noopener"
							target="_blank"
						>
							{t('legal.privacy.block152')}
						</a>
					</p>
				</li>
			</ul>
			<h2>{t('legal.privacy.block153')}</h2>
			<h3>{t('legal.privacy.block154')}</h3>
			<p>{t('legal.privacy.block155')}</p>
			<ul>
				<li>
					<strong>{t('legal.privacy.block156')}</strong> {t('legal.privacy.block157')}
				</li>
				<li>
					<strong>{t('legal.privacy.block158')}</strong> {t('legal.privacy.block159')}
				</li>
				<li>
					<strong>{t('legal.privacy.block160')}</strong> {t('legal.privacy.block161')}
				</li>
				<li>
					<strong>{t('legal.privacy.block162')}</strong> {t('legal.privacy.block163')}
				</li>
				<li>
					<strong>{t('legal.privacy.block164')}</strong> {t('legal.privacy.block165')}
				</li>
				<li>
					<strong>{t('legal.privacy.block166')}</strong> {t('legal.privacy.block167')}
				</li>
			</ul>
			<p>{t('legal.privacy.block168')}</p>
			<h3>{t('legal.privacy.block169')}</h3>
			<p>{t('legal.privacy.block170')}</p>
			<p>{t('legal.privacy.block171')}</p>
			<ul>
				<li>
					<strong>{t('legal.privacy.block172')}</strong> {t('legal.privacy.block173')}
				</li>
				<li>
					<strong>{t('legal.privacy.block174')}</strong> {t('legal.privacy.block175')}
				</li>
				<li>
					<strong>{t('legal.privacy.block176')}</strong> {t('legal.privacy.block177')}
				</li>
				<li>
					<strong>{t('legal.privacy.block178')}</strong> {t('legal.privacy.block179')}
				</li>
				<li>
					<strong>{t('legal.privacy.block180')}</strong> {t('legal.privacy.block181')}
				</li>
				<li>
					<strong>{t('legal.privacy.block182')}</strong> {t('legal.privacy.block183')}
				</li>
			</ul>
			<h3>{t('legal.privacy.block184')}</h3>
			<p>{t('legal.privacy.block185')}</p>
			<p>{t('legal.privacy.block186')}</p>
			<h2>{t('legal.privacy.block187')}</h2>
			<p>{t('legal.privacy.block188')}</p>
			<h3>{t('legal.privacy.block189')}</h3>
			<p>{t('legal.privacy.block190')}</p>
			<p>{t('legal.privacy.block191')}</p>
			<ul>
				<li>
					<p>
						<strong>{t('legal.privacy.block192')}</strong>
					</p>
					<p>{t('legal.privacy.block193')}</p>
					<p>{t('legal.privacy.block194')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block195')}</strong>
					</p>
					<p>{t('legal.privacy.block196')}</p>
					<p>{t('legal.privacy.block197')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block198')}</strong>
					</p>
					<p>{t('legal.privacy.block199')}</p>
					<p>{t('legal.privacy.block200')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block201')}</strong>
					</p>
					<p>{t('legal.privacy.block202')}</p>
					<p>{t('legal.privacy.block203')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block204')}</strong>
					</p>
					<p>{t('legal.privacy.block205')}</p>
					<p>{t('legal.privacy.block206')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block207')}</strong>
					</p>
					<p>{t('legal.privacy.block208')}</p>
					<p>{t('legal.privacy.block209')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block210')}</strong>
					</p>
					<p>{t('legal.privacy.block211')}</p>
					<p>{t('legal.privacy.block212')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block213')}</strong>
					</p>
					<p>{t('legal.privacy.block214')}</p>
					<p>{t('legal.privacy.block215')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block216')}</strong>
					</p>
					<p>{t('legal.privacy.block217')}</p>
					<p>{t('legal.privacy.block218')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block219')}</strong>
					</p>
					<p>{t('legal.privacy.block220')}</p>
					<p>{t('legal.privacy.block221')}</p>
				</li>
				<li>
					<p>
						<strong>{t('legal.privacy.block222')}</strong>
					</p>
					<p>{t('legal.privacy.block223')}</p>
					<p>{t('legal.privacy.block224')}</p>
				</li>
			</ul>
			<p>{t('legal.privacy.block225')}</p>
			<ul>
				<li>{t('legal.privacy.block226')}</li>
				<li>{t('legal.privacy.block227')}</li>
				<li>
					{t('legal.privacy.block228')}
					<ul>
						<li>{t('legal.privacy.block229')}</li>
						<li>{t('legal.privacy.block230')}</li>
					</ul>
				</li>
			</ul>
			<h3>{t('legal.privacy.block231')}</h3>
			<p>{t('legal.privacy.block232')}</p>
			<ul>
				<li>
					<strong>{t('legal.privacy.block233')}</strong>
					{t('legal.privacy.block234')}
				</li>
				<li>
					<strong>{t('legal.privacy.block235')}</strong>
					{t('legal.privacy.block236')}
				</li>
				<li>
					<strong>{t('legal.privacy.block237')}</strong>
					{t('legal.privacy.block238')}
				</li>
				<li>
					<strong>{t('legal.privacy.block239')}</strong>
					{t('legal.privacy.block240')}
				</li>
			</ul>
			<h3>{t('legal.privacy.block241')}</h3>
			<p>{t('legal.privacy.block242')}</p>
			<ul>
				<li>{t('legal.privacy.block243')}</li>
				<li>{t('legal.privacy.block244')}</li>
				<li>{t('legal.privacy.block245')}</li>
				<li>{t('legal.privacy.block246')}</li>
				<li>{t('legal.privacy.block247')}</li>
				<li>{t('legal.privacy.block248')}</li>
				<li>{t('legal.privacy.block249')}</li>
			</ul>
			<p>{t('legal.privacy.block250')}</p>
			<p>{t('legal.privacy.block251')}</p>
			<h3>{t('legal.privacy.block252')}</h3>
			<p>{t('legal.privacy.block253')}</p>
			<ul>
				<li>{t('legal.privacy.block254')}</li>
				<li>{t('legal.privacy.block255')}</li>
				<li>{t('legal.privacy.block256')}</li>
				<li>{t('legal.privacy.block257')}</li>
			</ul>
			<p>{t('legal.privacy.block258')}</p>
			<p>{t('legal.privacy.block259')}</p>
			<h3>{t('legal.privacy.block260')}</h3>
			<p>{t('legal.privacy.block261')}</p>
			<p>{t('legal.privacy.block262')}</p>
			<p>{t('legal.privacy.block263')}</p>
			<ul>
				<li>{t('legal.privacy.block264')}</li>
				<li>{t('legal.privacy.block265')}</li>
				<li>{t('legal.privacy.block266')}</li>
				<li>{t('legal.privacy.block267')}</li>
			</ul>
			<h3>{t('legal.privacy.block268')}</h3>
			<p>{t('legal.privacy.block269')}</p>
			<ul>
				<li>{t('legal.privacy.block270')}</li>
				<li>{t('legal.privacy.block271')}</li>
				<li>{t('legal.privacy.block272')}</li>
				<li>{t('legal.privacy.block273')}</li>
				<li>{t('legal.privacy.block274')}</li>
			</ul>
			<h3>{t('legal.privacy.block275')}</h3>
			<p>{t('legal.privacy.block276')}</p>
			<p>{t('legal.privacy.block277')}</p>
			<p>{t('legal.privacy.block278')}</p>
			<h3>{t('legal.privacy.block279')}</h3>
			<p>{t('legal.privacy.block280')}</p>
			<ul>
				<li>
					<strong>{t('legal.privacy.block281')}</strong> {t('legal.privacy.block282')}
				</li>
				<li>
					<strong>{t('legal.privacy.block283')}</strong> {t('legal.privacy.block284')}
					<ul>
						<li>{t('legal.privacy.block285')}</li>
						<li>{t('legal.privacy.block286')}</li>
						<li>{t('legal.privacy.block287')}</li>
						<li>{t('legal.privacy.block288')}</li>
						<li>{t('legal.privacy.block289')}</li>
						<li>
							{t('legal.privacy.block290')}
							<ul>
								<li>{t('legal.privacy.block291')}</li>
								<li>{t('legal.privacy.block292')}</li>
							</ul>
						</li>
					</ul>
				</li>
				<li>
					<strong>{t('legal.privacy.block293')}</strong> {t('legal.privacy.block294')}
				</li>
				<li>
					<strong>{t('legal.privacy.block295')}</strong> {t('legal.privacy.block296')}
					<ul>
						<li>{t('legal.privacy.block297')}</li>
						<li>{t('legal.privacy.block298')}</li>
						<li>{t('legal.privacy.block299')}</li>
						<li>{t('legal.privacy.block300')}</li>
						<li>{t('legal.privacy.block301')}</li>
						<li>{t('legal.privacy.block302')}</li>
						<li>{t('legal.privacy.block303')}</li>
						<li>{t('legal.privacy.block304')}</li>
						<li>{t('legal.privacy.block305')}</li>
					</ul>
				</li>
				<li>
					<strong>{t('legal.privacy.block306')}</strong> {t('legal.privacy.block307')}
					<ul>
						<li>{t('legal.privacy.block308')}</li>
						<li>{t('legal.privacy.block309')}</li>
						<li>{t('legal.privacy.block310')}</li>
						<li>{t('legal.privacy.block311')}</li>
					</ul>
				</li>
			</ul>
			<h3>{t('legal.privacy.block312')}</h3>
			<p>{t('legal.privacy.block313')}</p>
			<ul>
				<li>{t('legal.privacy.block314')}</li>
			</ul>
			<p>{t('legal.privacy.block315')}</p>
			<p>{t('legal.privacy.block316')}</p>
			<ul>
				<li>{t('legal.privacy.block317')}</li>
				<li>{t('legal.privacy.block318')}</li>
			</ul>
			<p>{t('legal.privacy.block319')}</p>
			<ul>
				<li>{t('legal.privacy.block320')}</li>
				<li>{t('legal.privacy.block321')}</li>
			</ul>
			<p>{t('legal.privacy.block322')}</p>
			<p>{t('legal.privacy.block323')}</p>
			<p>{t('legal.privacy.block324')}</p>
			<h3>{t('legal.privacy.block325')}</h3>
			<p>{t('legal.privacy.block326')}</p>
			<p>{t('legal.privacy.block327')}</p>
			<p>{t('legal.privacy.block328')}</p>
			<h4>{t('legal.privacy.block329')}</h4>
			<p>{t('legal.privacy.block330')}</p>
			<ul>
				<li>
					{t('legal.privacy.block331')}{' '}
					<a
						href="http://www.networkadvertising.org/choices/"
						rel="external nofollow noopener"
						target="_blank"
					>
						{t('legal.privacy.block332')}
					</a>
				</li>
				<li>
					{t('legal.privacy.block333')}{' '}
					<a
						href="http://www.youronlinechoices.com/"
						rel="external nofollow noopener"
						target="_blank"
					>
						{t('legal.privacy.block334')}
					</a>
				</li>
				<li>
					{t('legal.privacy.block335')}{' '}
					<a
						href="http://optout.aboutads.info/?c=2&amp;lang=EN"
						rel="external nofollow noopener"
						target="_blank"
					>
						{t('legal.privacy.block336')}
					</a>
				</li>
			</ul>
			<p>{t('legal.privacy.block337')}</p>
			<h4>{t('legal.privacy.block338')}</h4>
			<p>{t('legal.privacy.block339')}</p>
			<ul>
				<li>{t('legal.privacy.block340')}</li>
				<li>{t('legal.privacy.block341')}</li>
			</ul>
			<p>{t('legal.privacy.block342')}</p>
			<h2>{t('legal.privacy.block343')}</h2>
			<p>{t('legal.privacy.block344')}</p>
			<p>{t('legal.privacy.block345')}</p>
			<h2>{t('legal.privacy.block346')}</h2>
			<p>{t('legal.privacy.block347')}</p>
			<p>{t('legal.privacy.block348')}</p>
			<h2>{t('legal.privacy.block349')}</h2>
			<p>{t('legal.privacy.block350')}</p>
			<p>{t('legal.privacy.block351')}</p>
			<h2>{t('legal.privacy.block352')}</h2>
			<p>{t('legal.privacy.block353')}</p>
			<p>{t('legal.privacy.block354')}</p>
			<p>{t('legal.privacy.block355')}</p>
			<h2>{t('legal.privacy.block356')}</h2>
			<p>{t('legal.privacy.block357')}</p>
			<p>{t('legal.privacy.block358')}</p>
			<h2>{t('legal.privacy.block359')}</h2>
			<p>{t('legal.privacy.block360')}</p>
			<p>{t('legal.privacy.block361')}</p>
			<p>{t('legal.privacy.block362')}</p>
			<h2>{t('legal.privacy.block363')}</h2>
			<p>{t('legal.privacy.block364')}</p>
			<ul>
				<li>{t('legal.privacy.block365')}</li>
			</ul>
		</LegalContent>
	);
}
