name: Deploy CubeDesk to Production
on:
    push:
        branches:
            - main

jobs:
    deploy-prod:
        uses: kash/cubedesk/.github/workflows/deploy.yaml@main
        with:
            ECR_REPOSITORY: cubedesk
            ECS_CLUSTER: cubedesk-prod
            ECS_SERVICE: cubedesk-prod
            TASK_DEFINITION: cubedesk-prod
            CONTAINER_NAME: Main
            DATABASE_SECRET_ID: prod/database
            S3_BUCKET: cubedesk
            ENV: production
            RESOURCES_BASE_URI: https://cdn.cubedesk.io/static
            DIST_BASE_URI: https://cdn.cubedesk.io/dist
        secrets:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
